In [28]:
import pandas as pd

In [29]:
train_X = pd.read_csv('../data/curated/cleaned_train_X.csv')
val_X = pd.read_csv('../data/curated/cleaned_val_X.csv')
test_X = pd.read_csv('../data/curated/cleaned_test_X.csv')

## One-hot Encode Categorical Data

In [30]:
encoded_train_X = pd.get_dummies(train_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])
encoded_val_X = pd.get_dummies(val_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])
encoded_test_X = pd.get_dummies(test_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])

In [31]:
encoded_train_X.drop(['Name', 'Ticket'], axis=1, inplace=True)
encoded_val_X.drop(['Name', 'Ticket'], axis=1, inplace=True)
encoded_test_X.drop(['Name', 'Ticket'], axis=1, inplace=True)

In [32]:
encoded_train_X

,Unnamed: 0,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,family_name_Youseff,family_name_Yousif,family_name_Yousseff,family_name_Yrois,family_name_Zabour,family_name_de Messemaeker,family_name_de Pelsmaeker,family_name_del Carlo,family_name_van Billiard,family_name_van Melkebeke
0,331,1,45.5,0,0,28.5000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,733,2,23.0,0,0,13.0000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,382,3,32.0,0,0,7.9250,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,704,3,26.0,1,0,7.8542,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,813,3,6.0,4,2,31.2750,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,106,3,21.0,0,0,7.6500,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
708,270,1,28.0,0,0,31.0000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
709,860,3,41.0,2,0,14.1083,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
710,435,1,14.0,1,2,120.0000,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
711,102,1,21.0,0,1,77.2875,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
for feature in encoded_test_X.columns:
    if encoded_test_X[feature].isna().sum() > 0:
        print(feature)

### PCA

In [34]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
def get_pca(encoded_train_X):
    scaler = StandardScaler()
    scaled_train_X = scaler.fit_transform(encoded_train_X)
    pca = PCA(n_components=32)
    principal_components = pca.fit_transform(scaled_train_X)
    principal_df = pd.DataFrame(data=principal_components)
    return principal_df

In [35]:
principal_train_df = get_pca(encoded_train_X)
principal_val_df = get_pca(encoded_val_X)
principal_test_df = get_pca(encoded_test_X)

In [36]:
principal_train_df.to_csv('../data/curated/final_train_X.csv')
principal_val_df.to_csv('../data/curated/final_val_X.csv')
principal_test_df.to_csv('../data/curated/final_train_X.csv')