In [1]:
import pandas as pd

/Users/devin/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
train_X = pd.read_csv('../data/curated/cleaned_train_X.csv')
val_X = pd.read_csv('../data/curated/cleaned_val_X.csv')
test_X = pd.read_csv('../data/curated/cleaned_test_X.csv')

## One-hot Encode Categorical Data

In [3]:
encoded_train_X = pd.get_dummies(train_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])
encoded_val_X = pd.get_dummies(val_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])
encoded_test_X = pd.get_dummies(test_X, columns=['Sex', 'Embarked', 'ticket_prefix', 'title', 'family_name'])

In [5]:
encoded_train_X

,Unnamed: 0,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,family_name_Youseff,family_name_Yousif,family_name_Yousseff,family_name_Yrois,family_name_Zabour,family_name_de Messemaeker,family_name_de Pelsmaeker,family_name_del Carlo,family_name_van Billiard,family_name_van Melkebeke
0,331,1,45.5,0,0,28.5000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,733,2,23.0,0,0,13.0000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,382,3,32.0,0,0,7.9250,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,704,3,26.0,1,0,7.8542,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,813,3,6.0,4,2,31.2750,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,106,3,21.0,0,0,7.6500,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
708,270,1,28.0,0,0,31.0000,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
709,860,3,41.0,2,0,14.1083,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
710,435,1,14.0,1,2,120.0000,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
711,102,1,21.0,0,1,77.2875,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
for feature in encoded_test_X.columns:
    if encoded_test_X[feature].isna().sum() > 0:
        print(feature)

### PCA

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
def get_pca(encoded_train_X):
    scaler = StandardScaler()
    scaled_train_X = scaler.fit_transform(encoded_train_X)
    pca = PCA(n_components=16)
    principal_components = pca.fit_transform(scaled_train_X)
    principal_df = pd.DataFrame(data=principal_components)
    return principal_df

In [8]:
principal_train_df = get_pca(encoded_train_X)
principal_val_df = get_pca(encoded_val_X)
principal_test_df = get_pca(encoded_test_X)

In [9]:
principal_train_df.to_csv('../data/curated/final_train_X.csv',index=False)
principal_val_df.to_csv('../data/curated/final_val_X.csv', index=False)
principal_test_df.to_csv('../data/curated/final_test_X.csv', index=False)

In [10]:
principal_train_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-1.714660,1.042466,-0.283547,1.598181,-0.508856,0.047852,0.394405,0.276904,-0.075719,0.325393,-0.753767,-0.023676,0.025373,-0.032619,-0.023496,0.088172
1,-1.859320,0.020111,-0.110539,0.471458,-0.195734,-0.489251,-0.002312,-0.133290,0.733792,-0.259561,0.119559,0.145176,-0.075664,0.030472,0.052024,0.037135
2,-2.766964,-0.665206,-0.823893,0.079674,0.471878,-0.241626,1.352090,-0.887944,0.604515,-1.923797,2.432953,-0.406664,-0.258690,2.602342,-0.723485,0.583632
3,-1.931863,-0.716636,0.079433,0.104605,0.009141,-0.340725,0.225559,0.240473,0.508442,-0.407499,0.299840,0.002185,-0.066932,0.001420,-0.032112,-0.074632
4,3.195152,-3.175035,0.990257,-0.211131,0.155439,-0.336773,0.414811,-0.350934,0.512927,-0.498261,-0.004685,0.161121,0.040058,0.054630,0.035727,-0.012084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,2.197985,-1.314370,-2.286139,-0.924057,0.169992,-0.284520,0.692384,-0.890646,-0.425105,-0.184288,-0.588713,-0.252436,-0.041727,-0.110753,-0.152325,-0.033105
708,-1.587663,0.629526,0.012697,1.076634,-0.477327,-0.141642,0.276628,-0.277188,-0.161766,0.331083,-0.630233,0.011445,-0.170349,-0.028760,0.101610,0.106538
709,-1.884857,-0.625169,0.250116,0.492973,0.018636,-0.226400,0.410707,0.633976,0.651001,-0.456206,0.349115,-0.032709,-0.043931,0.003009,-0.037807,-0.079905
710,3.300688,-0.564961,0.274254,1.448050,-0.550114,0.623953,0.377034,-0.789820,0.289307,0.032610,-0.695101,0.409461,-0.010989,0.080356,0.104670,0.152248
711,-1.048009,0.435373,0.780308,1.416132,-0.675405,-0.050343,0.334754,-0.527364,-0.686722,0.567797,-1.034242,0.171525,0.083562,-0.039828,0.031560,0.144071